edition = "2021"

merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

# indentation
hard_tabs = true

# line width
max_width = 100
fn_call_width = 80
chain_width = 40
single_line_if_else_max_width = 100

# layout
match_block_trailing_comma = false
